# Generated by Django 3.2.4 on 2021-06-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_name',
            new_name='email',
        ),
    ]
